name: ML Client CI/CD

on:
  push:
    branches:
      - main
      - master
      - fixes
      - feature/**
    paths: 
      - machine-learning-client/**'
      - 'face_recog.py'
      - 'get_playlist.py'
      - 'requirements.txt'
      - '.github/workflows/ml-client-ci.yml'

  pull_request:
    branches:
      - main
      - master
      - fixes
      - feature/**
    paths:
      - 'machine-learning-client/**'
      - '.github/workflows/ml-client-ci.yml'

jobs:
  build-and-test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
     
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Install dependencies
        working-directory: machine-learning
        run: |
          pip install -r requirements.txt

      - name: Run tests
        env:
          MONGO_URI: ${{ secrets.MONGO_URI }}
        working-directory: machine-learning
        run: pytest tests/

      - name: Build Docker image
        run: |
          docker build -t ${{ secrets.DOCKERHUB_USERNAME }}/ml-client:latest machine-learning

      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Push Docker image
        run: |
          docker push ${{ secrets.DOCKERHUB_USERNAME }}/ml-client:latest
  
      - name: Deploy to DigitalOcean Droplet
        uses: appleboy/ssh-action@v0.1.6
        with:
          host: ${{ secrets.DIGITALOCEAN_HOST }}
          username: ${{ secrets.DIGITALOCEAN_USER }}
          key: ${{ secrets.DIGITALOCEAN_SSH_KEY }}
          script: |
            cd 5-final-five-timers-club/
            git pull origin main
            docker-compose down
            docker-compose up --build -d
            