name: ML Client CI

on:
  push:
    branches:
      - main
      - master
      - fixes
      - feature/**
    paths: 
      - machine-learning-client/**'
      - 'face_recog.py'
      - 'get_playlist.py'
      - 'requirements.txt'
      - '.github/workflows/ml-client-ci.yml'

  pull_request:
    branches:
      - main
      - master
      - fixes
      - feature/**
    paths:
      - 'machine-learning-client/**'
      - '.github/workflows/ml-client-ci.yml'

jobs:
  build-and-test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
     
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.x'

      - name: Install dependencies
        working-directory: machine-learning
        run: |
          pip install -r requirements.txt

      - name: Run tests
        working-directory: machine-learning
        run: pytest tests/

      - name: Build Docker image
        run: |
          docker build -t ${{ secrets.DOCKERHUB_USERNAME }}/ml-client:latest machine-learning

      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Push Docker image
        run: |
          docker push ${{ secrets.DOCKERHUB_USERNAME }}/ml-client:latest