name: Web App CI

on:
  push:
    branches: [main]
    paths:
      - 'web-app/**'
      - 'app.py'
      - 'requirements.txt'
      - '.github/workflows/web-cicd.yml'
  
  pull_request:
    branches: [main]
    paths:
      - 'web-app/**'
      - '.github/workflows/web-cicd.yml'

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: 3.11
      
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          pip install pytest
      
      - name: Create .env file
        run: |
          echo "FLASK_ENV=development" >> .env
          echo "FLASK_PORT=5000" >> .env
          echo "DEBUG=True" >> .env
          echo "MONGO_URI=${{ secrets.MONGO_URI }}" >> .env
          echo "MONGO_DBNAME=${{ secrets.MONGO_DBNAME }}" >> .env
          echo "SECRET_KEY=${{ secrets.SECRET_KEY }}" >> .env

      - name: Wait for services to be ready
        run: |
          echo "Waiting for web and ml services..."
          until curl -s http://localhost:5001 || [ $SECONDS -ge 60 ]; do sleep 2; done