name: Web App CI

on:
  push:
    branches: [ main, master ]
  pull_request:
    branches: [ main, master ]
  workflow_dispatch:

jobs:
  build-and-test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.x'
      - name: Install dependencies
        working-directory: web-app
        run: pip install -r requirements
      - name: Install test dependencies
        run: pip install pytest mongomock coverage
      - name: Run tests with coverage
        working-directory: web-app
        run: |
          coverage run -m pytest --maxfail=1 --disable-warnings -q web-app/tests
          coverage xml
      - name: Build Docker image
        run: |
          docker build -t ${{ secrets.DOCKERHUB_USERNAME }}/web-app:latest web-app
      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - name: Push Docker image
        run: |
          docker push ${{ secrets.DOCKERHUB_USERNAME }}/web-app:latest
      - name: Deploy to DigitalOcean
        if: secrets.DO_TOKEN && secrets.DO_APP_ID
        uses: digitalocean/action-doctl@v2
        with:
          token: ${{ secrets.DO_TOKEN }}

      - name: Update DO App Spec
        if: secrets.DO_TOKEN && secrets.DO_APP_ID
        run: doctl apps update ${{ secrets.DO_APP_ID }} --spec ./web-app/doapp.yaml