name: Web App CI/CD

on:
  push:
    branches:
      - main
      - master
      - fixes
      - feature/**
  pull_request:
    branches:
      - main
      - master
      - fixes
      - feature/**
  workflow_dispatch:

jobs:
  build-and-test:
    env:
      MONGO_URI: mongodb://localhost:27017/
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.x'
      - name: Install dependencies
        working-directory: web-app
        run: pip install -r requirements.txt
      - name: Install test dependencies
        run: pip install pytest mongomock coverage
      - name: Run tests with coverage
        working-directory: web-app
        run: |
          coverage run -m pytest --maxfail=1 --disable-warnings -q tests
          coverage xml
      - name: Build Docker image
        run: |
          docker build -t ${{ secrets.DOCKERHUB_USERNAME }}/web-app:latest web-app
      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - name: Push Docker image
        run: |
          docker push ${{ secrets.DOCKERHUB_USERNAME }}/web-app:latest

      - name: Deploy to DigitalOcean Droplet
        uses: appleboy/ssh-action@v0.1.6
        with:
          host: ${{ secrets.DIGITALOCEAN_HOST }}
          username: ${{ secrets.DIGITALOCEAN_USER }}
          key: ${{ secrets.DIGITALOCEAN_SSH_KEY }}
          script: |
            cd ~/5-final-five-timers-club
            git pull origin main
            docker-compose down
            docker-compose up --build -d
            